baseURL = "https://thatgurjot.com"
languageCode = "en"
defaultContentLanguage = "en"                             # en
title = "That Gurjot"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = "even"
enableGitInfo = false # use git commit log to generate lastmod record

# Syntax highlighting by Chroma. NOTE: Don't enable `highlightInClient` and `chroma` at the same time!
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

paginate = 5                                              # 首页每页显示的文章数
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name ↓        

[author]                  # essential                     # 必需
  name = "Gurjot."

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # 配置目录
  name = "home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "about"
  weight = 30
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "newsletter"
  weight = 40
  identifier = "newsletter"
  url = "/newsletter/"

[params]
  version = "4.x"           # Used to give a friendly message when you have an incompatible update
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda

  since = "2015"            # Site creation time          
  # use public git repo url to link lastmod git commit, enableGitInfo should be true.
  gitRepo = "https://github.com/gsidhu/thatgurjot"

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "G."        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["thatgurjot", "blog", "portfolio"]
  description = "Witness the normal."

  # paginate of archives, tags and categories
  archivePaginate = 20

  # show 'xx Posts In Total' in archive page ?
  showArchiveCount = false

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?
  moreMeta = false

  # Syntax highlighting by highlight.js
  highlightInClient = false

  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true
  autoCollapseToc = false   # Auto expand and collapse toc

  # mathjax
  mathjax = false           # see https://www.mathjax.org/
  mathjaxEnableSingleDollar = false
  mathjaxEnableAutoNumber = false
  mathjaxUseLocalFiles = false  # You should install mathjax in `your-site/static/lib/mathjax`

  postMetaInFooter = true   # contain author, lastMod, markdown link, license
  linkToMarkDown = false    # Only effective when hugo will output .md files.
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []
  customJS = []

  uglyURLs = false          # please keep same with uglyurls setting

  # scripts
  scrollama = '<script type="text/javascript" src="../js/intersection-observer.js"></script><script type="text/javascript" src="../js/scrollama.min.js"></script>'  
  jquery = '<script type="text/javascript" src="../js/jquery.min.js"></script>'
  slideout = '<script type="text/javascript" src="../js/slideout.min.js"></script>'

  [params.publicCDN]        # load these files from public cdn
    enable = true    
    fontawesome = '<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/js/all.min.js" crossorigin="anonymous"></script>'

  [params.social]                                         # 社交链接
    a-email = "mailto:contact@thatgurjot.com"
    c-twitter = "https://twitter.com/thatgurjot"
    g-github = "https://github.com/gsidhu"

# See https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true      # 12.214.31.144 -> 12.214.31.0
  [privacy.youtube]
    privacyEnhanced = true

[markup.goldmark.renderer]
unsafe= true

# 将下面这段配置取消注释可以使 hugo 生成 .md 文件
# Uncomment these options to make hugo output .md files.
#[mediaTypes]
#  [mediaTypes."text/plain"]
#    suffixes = ["md"]
#
#[outputFormats.MarkDown]
#  mediaType = "text/plain"
#  isPlainText = true
#  isHTML = false
#
#[outputs]
#  home = ["HTML", "RSS"]
#  page = ["HTML", "MarkDown"]
#  section = ["HTML", "RSS"]
#  taxonomy = ["HTML", "RSS"]
#  taxonomyTerm = ["HTML"]
