baseurl: "https://thatgurjot.com"
languageCode: "en"
defaultContentLanguage: "en"
title: "That Gurjot"
preserveTaxonomyNames: true
enableRobotsTXT: true
enableEmoji: true
theme: "hugo-tania-mod"
paginate: 5


params:
  author: "Gurjot."
  titleEmoji: 'G.'
  description: "That Gurjot's digital garden where he rants about education, showcases his projects and fulfills his sense of purpose."
  ogimage: '/Mysterious-Turban-Man.png'
  socialOptions:
    email: mailto:contact@thatgurjot.com
    github: https://github.com/gsidhu
    twitter: https://twitter.com/thatgurjot
  uglyURLs: false
  archivePaginate: 20
  since: 2015

menu:
  header:
    - name: who
      url: "/about"
      weight: 10
    - name: what
      url: "/what"
      weight: 20
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

